#
# Official YAML website: http://www.yaml.org/
#
# Google's YAML reference for Google App Engine: https://developers.google.com/appengine/docs/python/config/appconfig
#

# A unique identifier for the application on Google App Engine
# hip-ether-283 is the test ID I'm using for this practice application.
application: hip-ether-283

# Code version; if this number is adjusted before uploading, GAE will retain the older version and allow me to roll back to it using the administrative console
version: 1

# This application runs on the python27 environment, API version 1; this is the only configuration supported by GAE at the moment
runtime: python27
api_version: 1

# This application is threadsafe, which means a single instance can handle several simultaneous requests
threadsafe: true



# Specify a list of URL patterns and descriptions of how they should be handled
# URL handler path patterns are tested in the order listed - so /stylesheets is checked before /.*
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: guestbook.application



# Declare library dependencies
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest